alta_socies/urls.py
from django.conf.urls import patterns, include, url

from .views import SessioMonedaListView, SessioMonedaCreateView
from .views import SessioAcollidaListView, SessioAcollidaCreateView, \
    SessioAcollidaUpdateView, SessioMonedaUpdateView
from .views import ProcesAltaAutoocupatDetailView

urlpatterns = patterns(

    'alta_socies.views',

    # -----------------
    # SOCIS AUTOOCUPATS
    # -----------------

    url(r'^rebutjar_proces_alta/(?P<id_proces>\d+)/$', 'rebutjar_proces_alta_autoocupat', name='rebutjar_proces'),

    url(r'^exportar_a_csv/$', 'exportar_a_csv', name='exportar_a_csv'),

    url(r'^autoocupat/resum/(?P<pk>\d+)/$', ProcesAltaAutoocupatDetailView.as_view(), name='resum_proces_alta_projecte_autoocupat'),

    url(r'^editar_sessio_moneda/(?P<pk>\d+)/$', SessioMonedaUpdateView.as_view(), name='editar_sessio_moneda'),

    url(r'^editar_sessio_acollida/(?P<pk>\d+)/$', SessioAcollidaUpdateView.as_view(), name='editar_sessio_acollida'),

    url(r'^llistat_sessio_acollida', SessioAcollidaListView.as_view(), name='llistat_sessio_acollida'),

    url(r'^crear_sessio_acollida', SessioAcollidaCreateView.as_view(), name='crear_sessio_acollida'),

    url(r'^llistat_sessio_moneda', SessioMonedaListView.as_view(), name='llistat_sessio_moneda'),

    url(r'^crear_sessio_moneda', SessioMonedaCreateView.as_view(), name='crear_sessio_moneda'),

    url(r'^generador_sessions/$',
        'generar_sessions',
        name='generador_sessions'),

    url(r'^sessions_del_mes/(?P<tipus>\w+)(/(?P<year>\d\d\d\d)/(?P<month>\d\d?))?$',
        'sessions_del_mes',
        name='sessions_del_mes'),

    url(r'^autoocupat/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/(?P<pas>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/llistat_proces_alta_autoocupat/$',
        'llistat_proces_alta_autoocupat',
        name='llistat_proces_alta_autoocupat'),

    url(r'^autoocupat/control-qualitat/$',
        'llistat_proces_alta_projecte_autoocupat_revisio_descripcions',
        name='llistat_proces_alta_projecte_autoocupat_revisio_descripcions'),

    url(r'^estadistiques_proces_alta_projecte_autoocupat/?$',
        'estadistiques_proces_alta_projecte_autoocupat',
        name='estadistiques_proces_alta_projecte_autoocupat'),

    url(r'^reassignacio_proces_alta_autoocupat/?$',
        'reassignacio_proces_alta_autoocupat',
        name='reassignacio_proces_alta_autoocupat'),

    # -----------------
    # SOCIS COOPERATIUS
    # -----------------
    url(r'^cooperatiu/$', 'cooperatiu', name='cooperatiu'),
)

facturacio/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(

    'facturacio.views',

    url(r'^llistat_quotes_trimestrals/$',                    'llistat_quotes_trimestrals',   name='llistat_quotes_trimestrals'),

    url(r'^crear_factura_emesa/$',                           'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^crear_factura_emesa/(?P<id_client>\d+)$',         'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^linies_factura_emesa/(?P<id_factura>\d+)$',       'editar_linies_factura_emesa',  name='editar_linies_factura_emesa'),
    url(r'^confirmar_factura_emesa/(?P<id_factura>\d+)$',    'confirmar_factura_emesa',      name='confirmar_factura_emesa'),
    url(r'^veure_factura_emesa/(?P<id_factura>\d+)$',        'veure_factura_emesa',          name='veure_factura_emesa'),

    url(r'^crear_factura_rebuda/$',                          'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^crear_factura_rebuda/(?P<id_proveidor>\d+)$',     'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^linies_factura_rebuda/(?P<id_factura>\d+)$',      'editar_linies_factura_rebuda', name='editar_linies_factura_rebuda'),
    url(r'^veure_factura_rebuda/(?P<id_factura>\d+)$',       'veure_factura_rebuda',         name='veure_factura_rebuda'),
    url(r'^validacio_factures_rebudes/$',                    'validacio_factures_rebudes',   name='validacio_factures_rebudes'),

    url(r'^resum_facturacio_projecte/$',                     'resum_facturacio_projecte',    name='resum_facturacio_projecte'),
    url(r'^resum_facturacio_projecte/(?P<id_projecte>\d+)$', 'resum_facturacio_projecte',    name='resum_facturacio_projecte'),

    url(r'^moviments/$',                                     'llistat_moviments',            name='moviments'),
    url(r'^moviments/(?P<id_projecte>\d+)$',                 'llistat_moviments',            name='moviments'),

    url(r'^llistat_projectes_autoocupats/$',                 'llistat_projectes_autoocupats', name='llistat_projectes_autoocupats'),

    url(r'^facturacio_per_proveidor/$', 'volum_facturacio_empresa', kwargs=dict(tipus='proveidor'), name='facturacio_per_proveidor'),
    url(r'^facturacio_per_client/$',    'volum_facturacio_empresa', kwargs=dict(tipus='client'),    name='facturacio_per_client'),


)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^socies/alta/', include('alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('facturacio.urls', namespace='facturacio')),

    url(r'^admin/',       include(admin.site.urls)),

    url(r'^/?$',           'inici.views.inici',                      name='inici'),
    url(r'^ge/$',          'inici.views.dashboard_gestio_economica', name='dashboard_gestio_economica'),
    url(r'^pao/$',         'facturacio.views.dashboard_facturacio',  name='dashboard_projecte_autoocupat'),
    url(r'^style-guide/$', 'inici.views.styleguide',                 name='styleguide'),

)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

facturacio/views.py
# coding=utf-8
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.forms import inlineformset_factory, modelformset_factory, TextInput
from django.http.response import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from facturacio.helpers import calcular_periode
from facturacio.models import LiniaFactura, Moviment
from projectes.models import ProjecteAutoocupat
from empreses.models import Empresa, Cooperativa
from .forms import FormCrearFacturaEmesa, FormConfirmarFacturaEmesa, FormCrearFacturaRebuda, \
    FormEditarFacturaRebuda, FormCercarValidacioFacturaRebuda, FormValidacioFacturaRebuda, FormSeleccioVolumFacturacio
from socies.models import PersonaUsuaria
from gestioci.settings import auth_groups
from .models import QuotaTrimestral, Factura, FacturaEmesa, FacturaRebuda, Trimestre, trobar_balanc_actual


def llistat_quotes_trimestrals(request):
    today = timezone.localtime(timezone.now()).date()

    dates_vigor = QuotaTrimestral.objects.order_by('-data_vigor').values_list('data_vigor').distinct()
    dates_vigor = [d[0] for d in dates_vigor]

    taules = []
    hem_passat_actual = 0

    for data_vigor in dates_vigor:

        taula = QuotaTrimestral.objects.filter(data_vigor=data_vigor).order_by('base_imposable_minima')

        if data_vigor > today:
            temps = 'futur'
        else:

            if data_vigor <= today and hem_passat_actual == 0:
                temps = 'present'
            else:
                temps = 'passat'

            hem_passat_actual += 1

        taules.append(dict(data_vigor=data_vigor,
                           taula=taula,
                           temps=temps))

        if hem_passat_actual > 1:
            break

    return render(
        request,
        'facturacio/llistat_quotes_trimestrals.html',
        dict(taules=taules)
    )


@login_required
def resum_facturacio_projecte(request, id_projecte=None):

    if id_projecte is None:
        projectes = _projectes(request.user)
        if not projectes:
            messages.error(request, u"No ets membre de referència de cap projecte autoocupat.")
            return redirect('inici')

        projecte = projectes[0]

    else:
        projectes = ProjecteAutoocupat.objects.filter(pk=id_projecte)

        if projectes.count():
                projecte = projectes[0]
        else:
            messages.error(request, u"No hi ha cap projecte autoocupat amb aquest identificador.")
            return redirect('inici')

        if request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists() or \
                projecte not in _projectes(request.user):

            messages.error(request, u"No tens permís per consultar la facturació de cap projecte autoocupat.")
            return redirect('inici')

    if 'periode' in request.GET:
        periode = request.GET.get('periode')
        (des_de, fins_a) = calcular_periode(periode)
    else:
        # assumim que el trimestre actual existeix ;)
        trimestre = Trimestre.trobar_trimestre(timezone.localtime(timezone.now()))
        periode = trimestre.nom
        des_de = trimestre.data_inici
        fins_a = trimestre.data_final

    if des_de:

        factures_emeses = projecte.factures_emeses(des_de, fins_a)
        factures_rebudes = projecte.factures_rebudes(des_de, fins_a)

        resum_emeses = factures_emeses.aggregate(
            Sum('base_total'),
            Sum('iva_total'),
            Sum('req_total'),
            Sum('import_total'))

        resum_rebudes = factures_rebudes.aggregate(
            Sum('base_total'),
            Sum('iva_total'),
            Sum('irpf_total'),
            Sum('import_total'))

    else:
        factures_emeses = FacturaEmesa.objects.none()
        factures_rebudes = FacturaRebuda.objects.none()
        resum_emeses = resum_rebudes = None

    return render(
        request,
        'facturacio/resum_facturacio_projecte.html',
        dict(
            projecte=projecte,
            periode=periode,
            des_de=des_de,
            fins_a=fins_a,
            factures_emeses=factures_emeses,
            factures_rebudes=factures_rebudes,
            resum_rebudes=resum_rebudes,
            resum_emeses=resum_emeses,
        )
    )


# això no és cap vista!!
def _projectes(user):
    try:
        persona = PersonaUsuaria.objects.get(usuari=user).persona
        resultat = persona.projectes_autoocupats.all()
    except PersonaUsuaria.DoesNotExist:
        resultat = ProjecteAutoocupat.objects.none()

    return resultat


@login_required
def veure_factura_emesa(request, id_factura):
    factura = get_object_or_404(FacturaEmesa, pk=id_factura)

    if not factura.usuari_pot_editar(request.user):
        return HttpResponseForbidden(u"aquesta factura no és teva")

    # potser ho podem questionar, però de moment les proformes no es mostren; s'editen.
    if not factura.numero:
        if factura.liniafactura_set.count():
            return redirect('facturacio:confirmar_factura_emesa', id_factura=factura.pk)
        else:
            return redirect('facturacio:editar_linies_factura_emesa', id_factura=factura.pk)

    resum_iva, resum_req, resum_totals = factura.calcular_resums()

    return render(
        request,
        'facturacio/veure_factura_emesa.html',
        dict(
            f=factura,
            resum_iva=resum_iva,
            resum_req=resum_req,
            resum_totals=resum_totals,
        )
    )


@login_required
def crear_factura_emesa(request, id_client=None):
    projectes = _projectes(request.user)
    if not projectes:
        messages.error(request, u"No ets membre de referència de cap projecte autoocupat.")
        return redirect('inici')

    if projectes.count() > 1:
        messages.error(request, u"No està previst que una persona pugui facturar des de més d'un projecte.")
        return redirect('inici')
    else:
        projecte = projectes[0]

    clients_habituals = projecte.clients()
    initial = {}
    if id_client:
        client_proposat = Empresa.objects.filter(pk=id_client)  # vull una queryset pq despres ens convé la "unió"
        if client_proposat.count():
            initial['client'] = client_proposat[0].id
            clients_habituals |= client_proposat

    form = None

    if clients_habituals.count():

        if request.method == 'POST':

            form = FormCrearFacturaEmesa(clients=clients_habituals, initial=initial, data=request.POST)

            if form.is_valid():
                factura = form.save(commit=False)
                factura.projecte = projecte
                factura.proveidor = projecte.cooperativa_assignada
                factura.save()

                return redirect('facturacio:editar_linies_factura_emesa', id_factura=factura.pk)

        else:

            form = FormCrearFacturaEmesa(clients=clients_habituals, initial=initial)

    return render(
        request,
        'facturacio/crear_factura_emesa.html',
        dict(
            form=form,
        )
    )


@login_required
def editar_linies_factura_emesa(request, id_factura):
    factura = get_object_or_404(FacturaEmesa, pk=id_factura)

    if not factura.usuari_pot_editar(request.user):
        return HttpResponseForbidden(u"aquesta factura no és teva")
    if not factura.pertany_a_trimestre_obert():
        return HttpResponseForbidden(
            u"aquesta factura no es pot editar per què pertany a un trimestre que ja està tancat")
    if factura.numero:
        return HttpResponseForbidden(u"aquesta factura ja no es pot editar")

    # TODO wouldn't it be nice to refactor all this crap out to views.py? to a custom Form or Formset?
    _extra_attrs = {'onchange': 'linia_modificada(event.target)',
                    'style': 'text-align:right;'}

    FormsetLinies = inlineformset_factory(FacturaEmesa,
                                          LiniaFactura,
                                          extra=3,
                                          fields=(
                                              'quantitat',
                                              'concepte',
                                              'preu_unitari',
                                              'tipus_iva',
                                              'tipus_req'),
                                          widgets={
                                              'quantitat': TextInput(attrs=_extra_attrs),
                                              'preu_unitari': TextInput(attrs=_extra_attrs),
                                              'tipus_iva': TextInput(attrs=_extra_attrs),
                                              'tipus_req': TextInput(attrs=_extra_attrs),
                                          })

    if request.method == 'POST':
        formset = FormsetLinies(data=request.POST, instance=factura)
        if formset.is_valid():
            formset.save()
            factura.save()  # força a actualitzar camps calculats

            if request.POST.get('anem_a') == 'seguent':
                return redirect('facturacio:confirmar_factura_emesa', id_factura=factura.pk)

            return redirect('facturacio:editar_linies_factura_emesa', id_factura=factura.pk)

    else:
        formset = FormsetLinies(instance=factura)

    return render(
        request,
        'facturacio/editar_linies_factura_emesa.html',
        dict(
            factura=factura,
            formset=formset
        )
    )


@login_required
def confirmar_factura_emesa(request, id_factura):
    factura = get_object_or_404(FacturaEmesa, pk=id_factura)

    if not factura.usuari_pot_editar(request.user):
        return HttpResponseForbidden(u"aquesta factura no és teva")
    if not factura.pertany_a_trimestre_obert():

facturacio/templates/facturacio/crear_factura_emesa.html
{% extends "simple.html" %}
{% load gci_tags %}

{#{% block titol_a_capcalera %}#}
{#{% endblock %}#}

{% block content %}

{# this should be above, inside titol_a_capcalera #}
<h1>Emissió d'una nova factura</h1>
{# end titol_a_capcalera #}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            {% if form %}
                <li>Començareu creant una factura «proforma»; La factura definitiva es genera al final d'aquest procés.</li>
                <li>Trieu el client i la data d'emissió.</li>
                <li>Proveu a començar a escriure al camp de sota el NIF o el nom de l'empresa.</li>
                <li>Si no hi surt, l'haureu de <a>buscar o donar d'alta</a>.</li>
                <li>La data de la factura ha de correspondre al trimestre en curs, o a l'anterior, si encara no està tancat.</li>
            {% else %}
                <li>No hi teniu cap client a la vostra llista; L'haureu de <a>buscar o donar d'alta</a>.</li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

{% if form %}
    <form method="POST">
        {% csrf_token %}
        {% form_field form.client %}
        {% form_field form.data %}
        <button class="radius button" type="submit">Crear factura proforma</button>
    </form>
{% endif %}

{% endblock %}

facturacio/templates/facturacio/dashboard_facturacio_projecte.html
{% extends "layout.html" %}
{% load gci_tags %}

{% block content %}
    <style>
        .currency {  {# TODO this does not belong here, should be moved to global style sheet #}
            white-space: nowrap;
        }
        .currency_negative {  {# TODO this does not belong here, should be moved to global style sheet #}
            white-space: nowrap;
            color: red;
        }
    </style>

    <div class="row">
        <div class="medium-12 columns">
            <div class="groups-container" data-masonry>
                {% if user.is_authenticated %}

                    <section class="group">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-balance-scale"></i> Balanç</h1>

                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{% url "facturacio:moviments" %}" class="button"><i class="fa fa-fw fa-list"></i> Consultar moviments</a>
                                </li>
                            </ul>
                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{% url "facturacio:crear_factura_emesa" %}" class="button"><i class="fa fa-fw fa-money"></i> Sol·licitar reintegrament</a>
                                </li>
                            </ul>


                            <table>
                                <tr>
                                    <th>Balanç al tancament de l'últim trimestre</th>
                                    <td class="text-right">
                                        {% if balanc_ultim_trimestre == None %}
                                            <em>N/A</em>
                                        {% else %}
                                            {% currency_value balanc_ultim_trimestre highlight_negative=True %}
                                        {% endif %}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Balanç actual</th>
                                    <td class="text-right">{% currency_value balanc_actual highlight_negative=True %}</td>
                                </tr>
                            </table>

                            <small><sup>*</sup> Valors positius al vostre favor; negatius (vermell) a favor de la cooperativa.</small>

                        </div>
                    </section>

                    <section class="group">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-folder"></i> Activitat per any i trimestre</h1>

                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{% url "facturacio:crear_factura_emesa" %}" class="button"><i class="fa fa-fw fa-plus"></i> Emetre una factura</a>
                                </li>
                            </ul>
                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{% url "facturacio:crear_factura_rebuda" %}" class="button"><i class="fa fa-fw fa-plus"></i> Enregistrar factura rebuda</a>
                                </li>
                            </ul>

                            <table>
                            <thead>
                                <th class="text-center">Any</th>
                                <th class="text-center">T1</th>
                                <th class="text-center">T2</th>
                                <th class="text-center">T3</th>
                                <th class="text-center">T4</th>
                                <th class="text-center">Total</th>
                            </thead>
                            <tbody>
                                {% for y, resum in activitat.items %}
                                <tr>
                                    <td class="text-center">{{ y }}</td>
                                    {% for t, c in resum.trimestres.items %}
                                        <td class="text-center">
                                            {% if c.emeses or c.rebudes %}
                                                <a
                                                    href="{% url "facturacio:resum_facturacio_projecte" id_projecte=projecte.id %}?periode={{ y }}T{{ t }}"
                                                    title="{{ c.emeses }} emes{{ c.emeses|pluralize:"a,es" }}&#10;{{ c.rebudes }} rebud{{ c.rebudes|pluralize:"a,es" }}"
                                                        >{{ c.emeses }}&nbsp;+&nbsp;{{ c.rebudes }}</a>
                                            {% else %}
                                                &nbsp;
                                            {% endif %}
                                        </td>
                                    {% endfor %}
                                    <td class="text-center">
                                        {% with resum.total as c %}
                                        <a
                                            href="{% url "facturacio:resum_facturacio_projecte" id_projecte=projecte.id %}?periode={{ y }}"
                                            title="{{ c.emeses }} emes{{ c.emeses|pluralize:"a,es" }}&#10;{{ c.rebudes }} rebud{{ c.rebudes|pluralize:"a,es" }}"
                                                >{{ c.emeses }}&nbsp;+&nbsp;{{ c.rebudes }}</a>
                                        {% endwith %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    </section>

                {% endif %}
                {% if FLAG_GECO %}
                    {% if user.is_authenticated %}
                        {# TODO: show section only to socies AO #}
                        <section class="group green">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-file-text-o"></i> Papeleos</h1>
                                <ul>
                                    <li><a href="#">Añadir factura</a></li>
                                    <li><a href="#">Añadir gasto</a></li>
                                    <li>…</li>
                                </ul>
                            </div>
                        </section>
                        {# TODO: show section only to GECO admins #}
                        <section class="group green">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-money"></i> Gestió Económica</h1>
                                <p>…</p>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}
                {% if FLAG_ALTA_SOCIES %}
                    {% if not user.is_authenticated %}
                        <section class="group">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-pencil"></i> Fes-te soci@ de la CIC</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                                <p>
                                    <a href="{% url 'alta_socies:cooperatiu' %}" class="radius button expand">Formulari de inscripció soci cooperatiu</a>
                                </p>
                                <hr/>
                                <h2>Quieres hacerte socio autoocupado?</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}
                {% if FLAG_FAQ %}
                    {% if not user.is_authenticated %}
                        <section class="group">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-flag"></i> Bienvenido al portal del socio!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                            </div>
                        </section>
                    {% endif %}
                    <section class="group blue">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-question-circle"></i> FAQs</h1>
                            <input type="text" placeholder="Buscar…">
                        </div>
                    </section>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

facturacio/templates/facturacio/llistat_projectes_autoocupats.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block titol_a_capcalera %}Relació de projectes autoocupats{% endblock %}

{% block content %}

    <style>
        .currency {  {# TODO this does not belong here, should be moved to global style sheet #}
            white-space: nowrap;
        }
        .currency_negative {  {# TODO this does not belong here, should be moved to global style sheet #}
            white-space: nowrap;
            color: red;
        }
    </style>

    <h1>Relació de projectes autoocupats</h1>

    <table>
    <thead>
        <tr>
            <th class="text-left">Projecte</th>
            <th class="text-right">Balanç últim trimestre</th>
            <th class="text-right">balanç trimestre actual</th>
        </tr>
    </thead>
    <tbody>

    {% for p in projectes %}

        <tr>
            <td>{{ p.instance.nom }}</td>
            <td class="text-right">
                {% if p.balanc_ultim_trimestre == None %}
                    <em>N/A</em>
                {% else %}
                    {% currency_value p.balanc_ultim_trimestre highlight_negative=True %}
                {% endif %}
            </td>
            <td class="text-right"><a href="{% url "facturacio:moviments" p.instance.pk %}">{% currency_value p.balanc_actual highlight_negative=True %}</a></td>
       </tr>

    {% empty %}
        <tr>
            <td class="text-center"><em>No hi ha cap projecte autoocupat actiu.</em></td>
            <td colspan="2">&nbsp;</td>
        </tr>
    {% endfor %}

    </tbody>
    </table>

{% endblock %}

facturacio/templates/facturacio/llistat_quotes_trimestrals.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block titol_a_capcalera %}Taula de quotes trimestrals{% endblock %}

{% block content %}

    {% for taula in taules %}

        <h3>
            {% if taula.temps == 'futur' %}Aquesta taula entrarà en vigor a partir de{% endif %}
            {% if taula.temps == 'present' %}Aquesta taula està en vigor des de{% endif %}
            {% if taula.temps == 'passat' %} Aquesta taula ja està obsoleta però va entrar en vigor el{% endif %}

            {{ taula.data_vigor|format_data }} (inclòs):
        </h3>

        <table>
        <thead>
        <tr>
            <th>A partir d'aquesta base imposable total del trimestre</th>
            <th>Correspon aquesta quota trimestral</th>
        </tr>
        </thead>
        <tbody>
        {% for fila in taula.taula %}
            <tr>
                <td>{{ fila.base_imposable_minima }}</td>
                <td>{{ fila.import_quota_trimestral }}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>

    {% endfor %}

{% endblock %}